# Generated by Django 5.1.5 on 2025-01-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durus', '0002_rename_title_lesson_shekh_remove_lesson_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio_files/'),
        ),
    ]
