# Generated by Django 5.1.5 on 2025-01-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durus', '0003_lesson_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='Title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
