# Generated by Django 5.1.5 on 2025-01-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durus', '0004_lesson_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='Darasa',
            field=models.CharField(default='', max_length=300),
        ),
    ]
