# Generated by Django 5.1.5 on 2025-01-18 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durus', '0005_alter_lesson_darasa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='Darasa',
            new_name='Description',
        ),
    ]
