# Generated by Django 5.1.5 on 2025-01-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durus', '0006_rename_darasa_lesson_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
