# Generated by Django 5.1.5 on 2025-01-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durus', '0007_alter_lesson_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
