# Generated by Django 5.1.5 on 2025-01-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durus', '0008_alter_lesson_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Events', models.CharField(max_length=200)),
                ('Shekh', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
