# Generated by Django 5.1.5 on 2025-01-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durus', '0009_newz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newz',
            old_name='location',
            new_name='Location',
        ),
        migrations.AddField(
            model_name='newz',
            name='Time',
            field=models.CharField(default='', max_length=20),
        ),
    ]
