# Generated by Django 5.1.5 on 2025-01-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durus', '0010_rename_location_newz_location_newz_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newz',
            name='Time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
