# Generated by Django 5.1.5 on 2025-01-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durus', '0012_alter_newz_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio_files/')),
                ('msomaji', models.CharField(max_length=200)),
            ],
        ),
    ]
