# Generated by Django 5.1.5 on 2025-01-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durus', '0014_qur_sura'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='downloadable_file',
            field=models.FileField(blank=True, null=True, upload_to='downloadable_files/'),
        ),
    ]
