# Generated by Django 5.1.5 on 2025-01-22 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durus', '0015_lesson_downloadable_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='downloadable_file',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='Title',
            new_name='Topic',
        ),
    ]
