# Generated by Django 5.1.5 on 2025-01-24 04:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durus', '0016_rename_downloadable_file_lesson_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newz',
            name='Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
