# Generated by Django 5.1.5 on 2025-01-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durus', '0017_alter_newz_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newz',
            name='Time',
            field=models.DateTimeField(default=''),
        ),
    ]
